In [40]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import DictVectorizer
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import export_text
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

In [2]:
data = 'https://github.com/alexeygrigorev/datasets/raw/refs/heads/master/jamb_exam_results.csv'
!wget $data

--2025-09-04 06:54:02--  https://github.com/alexeygrigorev/datasets/raw/refs/heads/master/jamb_exam_results.csv
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/alexeygrigorev/datasets/refs/heads/master/jamb_exam_results.csv [following]
--2025-09-04 06:54:02--  https://raw.githubusercontent.com/alexeygrigorev/datasets/refs/heads/master/jamb_exam_results.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 391501 (382K) [text/plain]
Saving to: ‘jamb_exam_results.csv’

jamb_exam_results.c 100%[===================>] 382.33K  --.-KB/s    in 0.02s

2025-09-04 06:54:02 (22.3 MB/s) - ‘jamb_exam_results.csv’ saved [391501/391501]

In [3]:
df = pd.read_csv('jamb_exam_results.csv')

In [4]:
df.head()

,JAMB_Score,Study_Hours_Per_Week,Attendance_Rate,Teacher_Quality,Distance_To_School,School_Type,School_Location,Extra_Tutorials,Access_To_Learning_Materials,Parent_Involvement,IT_Knowledge,Student_ID,Age,Gender,Socioeconomic_Status,Parent_Education_Level,Assignments_Completed
0,192,22,78,4,12.4,Public,Urban,Yes,Yes,High,Medium,1,17,Male,Low,Tertiary,2
1,207,14,88,4,2.7,Public,Rural,No,Yes,High,High,2,15,Male,High,NaN,1
2,182,29,87,2,9.6,Public,Rural,Yes,Yes,High,Medium,3,20,Female,High,Tertiary,2
3,210,29,99,2,2.6,Public,Urban,No,Yes,Medium,High,4,22,Female,Medium,Tertiary,1
4,199,12,98,3,8.8,Public,Urban,No,Yes,Medium,Medium,5,22,Female,Medium,Tertiary,1

In [10]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
df.columns

Index(['jamb_score', 'study_hours_per_week', 'attendance_rate',
       'teacher_quality', 'distance_to_school', 'school_type',
       'school_location', 'extra_tutorials', 'access_to_learning_materials',
       'parent_involvement', 'it_knowledge', 'age', 'gender',
       'socioeconomic_status', 'parent_education_level',
       'assignments_completed'],
      dtype='object')

In [7]:
del df['student_id']

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   jamb_score                    5000 non-null   int64
 1   study_hours_per_week          5000 non-null   int64
 2   attendance_rate               5000 non-null   int64
 3   teacher_quality               5000 non-null   int64
 4   distance_to_school            5000 non-null   float64
 5   school_type                   5000 non-null   object
 6   school_location               5000 non-null   object
 7   extra_tutorials               5000 non-null   object
 8   access_to_learning_materials  5000 non-null   object
 9   parent_involvement            5000 non-null   object
 10  it_knowledge                  5000 non-null   object
 11  age                           5000 non-null   int64
 12  gender                        5000 non-null   object
 13  socioeconomic_status          5000 non-null   object
 14  parent_education_level        5000 non-null   object
 15  assignments_completed         5000 non-null   int64
dtypes: float64(1), int64(6), object(9)
memory usage: 625.1+ KB

In [13]:
df = df.fillna(0)

In [16]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)

y_train = df_train.jamb_score.values
y_val = df_val.jamb_score.values

del df_train['jamb_score']
del df_val['jamb_score']

In [32]:
train_dict = df_train.to_dict(orient='records')
dv = DictVectorizer(sparse=True)
X_train = dv.fit_transform(train_dict)

val_dict = df_val.to_dict(orient='records')
X_val = dv.transform(val_dict)

In [33]:
dt = DecisionTreeRegressor(max_depth=1)
dt.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=1)

In [34]:
print(export_text(dt, feature_names=list(dv.get_feature_names_out())))

|--- study_hours_per_week <= 18.50
|   |--- value: [155.24]
|--- study_hours_per_week >  18.50
|   |--- value: [188.59]

In [35]:
rf = RandomForestRegressor(n_estimators=10, random_state=1, n_jobs=-1)
rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, n_jobs=-1, random_state=1)

In [42]:
y_pred = rf.predict(X_val)
RMSE = np.sqrt(mean_squared_error(y_val, y_pred))
print('RSME = ', RMSE)

RSME =  42.13724207871227

In [64]:
def rf_parameter_tuning(n_estimators, max_depth):
    rf = RandomForestRegressor(n_estimators=n_estimators,
                               max_depth = max_depth,
                               random_state=1, 
                               n_jobs=-1)
    rf.fit(X_train, y_train)

    y_pred = rf.predict(X_val)
    RSME = np.sqrt(mean_squared_error(y_val, y_pred))
    scores.append(RSME)
        
    return scores

In [66]:
n_estimators = np.arange(10, 201, 10)
max_depth = None
scores = []

for n in n_estimators:
    scores = rf_parameter_tuning(n, max_depth)   

est_screen = pd.DataFrame({
    "n_estimators": values,
    "RMSE": scores
})

est_screen.round(3)

    n_estimators    RMSE
0             10  42.137
1             20  41.461
2             30  41.106
3             40  40.917
4             50  40.852
5             60  40.784
6             70  40.677
7             80  40.539
8             90  40.504
9            100  40.517
10           110  40.593
11           120  40.625
12           130  40.651
13           140  40.595
14           150  40.597
15           160  40.604
16           170  40.628
17           180  40.641
18           190  40.631
19           200  40.601

In [69]:
n_estimators = np.arange(10, 201, 10)
max_depth = [10, 15, 20, 25]
scores = []
scores_maxDepth = []

for m in max_depth:
    for n in n_estimators:
        scores = rf_parameter_tuning(n, m)
    scores_maxDepth.append(np.mean(scores))

In [71]:
scores_maxDepth

[np.float64(40.39249798892396),
 np.float64(40.56388985689364),
 np.float64(40.62250467853885),
 np.float64(40.663844923811155)]